# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build server

on:
  push:
    branches:
    - master

    # This specifically builds only the server projects.
    # Everything else can be ignored.
    paths:
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'deps/ZipArchive/**'
      - 'deps/zlib/**'
      - 'deps/zlib-msvc/**'
      - 'Server/AIServer/**'
      - 'Server/Aujard/**'
      - 'Server/Ebenezer/**'
      - 'Server/ItemManager/**'
      - 'Server/shared/**'
      - 'Server/VersionManager/**'
      - 'Client/N3Base/My_3DStruct.h'
      - 'Client/N3Base/N3ShapeMgr.h'
      - 'Client/N3Base/N3ShapeMgr.cpp'
      - 'Server.sln'
      - 'ThirdParty.sln'

  pull_request:
    branches:
    - master

    # This specifically builds only the server projects.
    # Everything else can be ignored.
    paths:
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'deps/ZipArchive/**'
      - 'deps/zlib/**'
      - 'deps/zlib-msvc/**'
      - 'Server/AIServer/**'
      - 'Server/Aujard/**'
      - 'Server/Ebenezer/**'
      - 'Server/ItemManager/**'
      - 'Server/shared/**'
      - 'Server/VersionManager/**'
      - 'Client/N3Base/My_3DStruct.h'
      - 'Client/N3Base/N3ShapeMgr.h'
      - 'Client/N3Base/N3ShapeMgr.cpp'
      - 'Server.sln'
      - 'ThirdParty.sln'
 
  merge_group:
  workflow_dispatch:
    
env:
  # We use a debug build for slightly faster build times
  BUILD_CONFIGURATION: Debug
  BUILD_PLATFORM: Win32

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build server
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration="${{env.BUILD_CONFIGURATION}}" /p:Platform="${{env.BUILD_PLATFORM}}" Server.sln
