# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build client

on:
  push:
    branches:
    - master

    # This specifically builds only the client (KnightOnline.exe) project.
    # Everything else can be ignored.
    paths:
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'Client/lib/**'
      - 'Client/N3Base/**'
      - 'Client/WarFare/**'
      - 'Server/shared/**'
      - 'All.sln'
      - 'Client.sln'

  pull_request:
    branches:
    - master

    # This specifically builds only the client (KnightOnline.exe) project.
    # Everything else can be ignored.
    paths:
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'Client/lib/**'
      - 'Client/N3Base/**'
      - 'Client/WarFare/**'
      - 'Server/shared/**'
      - 'All.sln'
      - 'Client.sln'
 
  merge_group:
  workflow_dispatch:
    
env:
  # We use a debug build for slightly faster build times
  BUILD_CONFIGURATION: Debug
  BUILD_PLATFORM: Win32

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build client
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration="${{env.BUILD_CONFIGURATION}}" /p:Platform="${{env.BUILD_PLATFORM}}" /p:NO_CLIENT_ASSETS="1" Client.sln
